export const BEGIN_FETCH_BREWERIES = "BEGIN_FETCH_BREWERIES";
export const FETCH_BREWERIES_SUCCESS = "FETCH_BREWERIES_SUCCESS";
export const FETCH_BREWERIES_FAILURE = "FETCH_BREWERIES_FAILURE";

export const BEGIN_ADD_BREWERY = "BEGIN_ADD_BREWERY";
export const ADD_BREWERY_SUCCESS = "ADD_BREWERY_SUCCESS";
export const ADD_BREWERY_FAILURE = "ADD_BREWERY_FAILURE";

export const FILTER_BREWERIES = "FILTER_BREWERIES";

