export const BEGIN_SEARCH_REQUEST = "BEGIN_SEARCH_REQUEST";
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
export const SEARCH_REQUEST_FAILURE = "SEARCH_REQUEST_FAILURE";

export const BEGIN_FETCH_BREWERIES = "BEGIN_FETCH_BREWERIES";
export const FETCH_BREWERIES_SUCCESS = "FETCH_BREWERIES_SUCCESS";
export const FETCH_BREWERIES_FAILURE = "FETCH_BREWERIES_FAILURE";

